title: Sitecity CKPEIIKA
description: Notes and resources on gas dynamics and ML
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  math_engine: mathjax
plugins:
  - kramdown-parser-gfm
exclude:
  - README.md
  - todo
